# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Flutter web app to Azure Web App - habeba

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Flutter web app
        run: flutter build web --release

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-app
          path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: flutter-web-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'habeba'  # Replace with your Azure Web App name
          slot-name: 'Production'
          package: build/web
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_8f739261fa1548c2a977358a00306ed0 }}
